### PR TITLE
File Import Issue, Custom widgets for ListField and DictField

### PR DESCRIPTION
**Pull request by rishabh3**
So we were working on the oclapi project as research project at our institution and we got some issues while setting and importing concepts/mappings. Hence we have come up with certain fixes which includes:
1) During install of requirements the link points to a page not found for django nonrel project hence we have fixed it and also given a work around.
2) We were getting errors like Not Implemented ListField and Dict Field for which we created our own custom model and custom form files which overrides the ListField and DictField from the djangotoolbox which can allow to use django admin without getting the error.
3) We also changed a little for importing mapping. So while importing mapping if there is some mismatch for a particular mapping the process used to stop so we added to catch this exception so we can decide to write failed mappings to some file and complete with all other mappings.
Note Mapping could fail because concept to which it is going to be mapped doesnot exist or the source to which it is mapped doesnot exist.

### CODE REVIEW

**Comment by rkorytkowski** [comment]
Did you notice that there are almost 7000 files touched by this PR? Why is that?

**Comment by rishabh3** [comment]
Actually i had some issues while merging my code with the original so i had
to remove the difference between the two files generated by git that is the
change i had made and the original code. This is because I had not forked
the project first. I think so that could be issue.

On Aug 11, 2017 21:01, "Rafal Korytkowski" <notifications@github.com> wrote:

Did you notice that there are almost 7000 files touched by this PR? Why is
that?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/OpenConceptLab/oclapi/pull/522#issuecomment-321845120>,
or mute the thread

**Comment by paynejd** [comment]
@rishabh3 Thanks for your interest. Could you tell us a bit more about your research institution and how you might use this tool? We are building a community of contributors always like to understand more how OCL is of value.

Also, could you point us to the files that you specifically updated? They are difficult to find since the list is 7,000 files long!

**Comment by rishabh3** [comment]
So i am a student at pes university. We were working on project of big data
in medicine where we worked with bahmni and openmrs. So we started working
with oclapi as a process to understand how things work , what is mapping
and what is concepts and many more and working with ocl helped us
understand the working of openmrs.
Yeah i will point to the files we updated but how should i send the list?

**Comment by paynejd** [comment]
Just text in a comment here is fine...

**Comment by rishabh3** [comment]
Yeah sure

**Comment by rishabh3** [comment]
Sorry for the late reply. Was quite busy last week
The files are as follows:
collection/models.py
concepts/models.py
mappings/importer.py
mappings/models.py
oclapi/customform.py
oclapi/custommodel.py
oclapi/models.py
orgs/models.py
sources/models.py
users/models.py
These were the files were we had made changes.

**Comment by rkorytkowski** [comment]
We cannot merge this PR as it adds too many files. Please create a new PR with just the modified files.

**Pull request closed without merging**
